# Make sample badges

name: "Sample badges"

on:
  push:
    branches:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  badges:
    name: "Make badges"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        total:
          - 40
          - 50
          - 60
          - 70
          - 80
          - 90
          - 100

    steps:
      - name: show it
        run: |
          echo coverage is ${{ matrix.total }}
